frase = str(input('Digite o seu nome completo?: '))
print('Assim fica com todas as letra maiúsculas:')
print(frase.upper())
print('Com todas minúsculas: ')
print(frase.lower())
nomediv = frase.split()
print(len(nomediv))